WebBanking/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanking.Data;
using WebBanking.Models;
using SimpleHashing;
using System.Text.RegularExpressions;
using X.PagedList;
using WebBanking.ViewModels;
using Microsoft.AspNetCore.Authorization;
using WebBanking.Repository;
using utils.Enums;

namespace WebBanking.Controllers
{
    [Authorize(Roles = nameof(RoleEnum.Customer))]

    public class CustomerController : Controller
    {
        private readonly WebBankContext _context;
        private readonly IUserRepository _userRepository;

        // Get Customer ID from Claims
        private int GetCustomerID() => Int32.Parse(HttpContext.User.FindFirst("CustomerID").Value);

        // Get Customer Object from DB
        private async Task<Customer> getActiveCustomerAsync() => await _context.Customer.FindAsync(GetCustomerID());

        public CustomerController(WebBankContext context, IUserRepository userRepository)
        {
            _context = context;
            _userRepository = userRepository;
        }


        // Display accounts
        // GET: Customer
        public async Task<IActionResult> Index()
        {
            var customer = await getActiveCustomerAsync();
            return View(customer);
        }

        // GET: Customer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var customer = await getActiveCustomerAsync();
            return View(customer);
        }

        //GET: Customer/Statements/5
        public async Task<IActionResult> Statements(int? id, int page = 1)
        {
            var transactions = await _context.Transaction.
                Where(x => x.AccountNumber == id).
                OrderByDescending(y => y.TransactionTimeUtc).
                ToPagedListAsync(page, 4);
            
            return View(transactions);
        }


        // GET: Customer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var customer = await getActiveCustomerAsync();
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerID,Name,TFN,Address,Suburb,State,Postcode,Mobile")] Customer customer)
        {
            // validate customer details to edit belong to logged in customer
            var customerID = GetCustomerID();
            if (customer.CustomerID != customerID)
                return NotFound();

            // validate model
            if (!ModelState.IsValid)
                return View(customer);

            // save changes
            _context.Update(customer);
            await _context.SaveChangesAsync();

            //return To details            
            return RedirectToAction(nameof(Details));
        }
    }
}

WebBanking/Controllers/SignupController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using utils.Enums;
using WebBanking.Data;
using WebBanking.Models;
using WebBanking.Repository;
using WebBanking.ViewModels;

namespace WebBanking.Controllers
{
    public class SignupController : Controller
    {
        private readonly WebBankContext _context;
        private readonly IUserRepository _userRepository;

        public SignupController(WebBankContext context, IUserRepository userRepository)
        {
            _context = context;
            _userRepository = userRepository;
        }

        private int? GetCustomerID()
        {
            try
            {
                return Int32.Parse(HttpContext.User.FindFirst("CustomerID").Value);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public IActionResult NewCustomer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NewCustomer(SignupUser model)
        {
            // validate initial deposit
            if ((model.AccountType == AccountType.Checking && model.InicialDeposit < 500) ||
                (model.AccountType == AccountType.Savings && model.InicialDeposit < 100))
                ModelState.AddModelError(nameof(model.InicialDeposit),
                    "The minimum balance to open a savings account is $100 and " +
                    "$500 for a checking account.");

            if (!ModelState.IsValid)
                return View();

            var rand = new Random();

            // Find an unused Custmer ID and Account number
            var activeCustomerIDs = await _context.Customer.
                Select(x => x.CustomerID).ToListAsync();

            var activeAccountNums = await _context.Account.
                Select(x => x.AccountNumber).ToListAsync();

            var activeLoginIDs = await _context.Users.
                Select(x => x.Id).ToListAsync();

            // Generate unique CustomerID, AccountNumber and LoginID
            var newCustomerID = rand.Next(1000, 9999);
            var newAccountNum = rand.Next(1000, 9999);
            var newLoginID = rand.Next(10000000, 99999999);

            while (activeCustomerIDs.Contains(newCustomerID))
                newCustomerID = rand.Next(1000, 9999);
            model.CustomerID = newCustomerID;

            while (activeAccountNums.Contains(newAccountNum))
                newAccountNum = rand.Next(1000, 9999);
            model.AccountNum = newAccountNum;

            while (activeLoginIDs.Contains(newLoginID))
                newLoginID = rand.Next(10000000, 99999999);
            model.LoginID = newLoginID.ToString();

            // Create Customer
            _context.Customer.Add(new Customer
            {
                CustomerID = newCustomerID,
                Name = model.Name
            });

            // Create Account
            _context.Account.Add(new Account
            {
                AccountNumber = newAccountNum,
                Type = model.AccountType,
                FreeTransactions = 4,
                Balance = model.InicialDeposit,
                CustomerID = newCustomerID,
            });

            // Add initial Deposit
            _context.Transaction.Add(new Transaction
            {
                AccountNumber = newAccountNum,
                Amount = model.InicialDeposit,
                Comment = "Opening Balance",
                TransactionTimeUtc = DateTime.UtcNow,
                TransactionType = TransactionType.Deposit,
            });
            await _context.SaveChangesAsync();

            // Add Logins
            var resultCreateUser = await _userRepository.CreateUserAsync(model);

            if (!resultCreateUser.Succeeded)
            {
                foreach (var error in resultCreateUser.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
            return View("SignupSuccess", model);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (!ModelState.IsValid)
                return View(login);



            var result = await _userRepository.LoginUserAsync(login);

            if (result == null)
            {
                ModelState.AddModelError(nameof(login.LoginID), $"User {login.LoginID} is locked out, please contact the Admin");

                return View(login);
            }

            if (result.Succeeded)
            {
                var user = _context.Users.FirstOrDefault(x => x.UserName == login.LoginID);

                HttpContext.Session.SetInt32(nameof(Customer.CustomerID), user.CustomerID.Value);
                HttpContext.Session.SetString(nameof(Customer.Name), user.Customer.Name);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(nameof(login.LoginID), "Invalid Credentials");

            return View(login);
        }

        [Authorize(Roles =nameof(RoleEnum.Customer))]
        public async Task<IActionResult> Logout()
        {
            await _userRepository.LogoutUserAsync();
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = nameof(RoleEnum.Customer))]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost, Authorize(Roles = nameof(RoleEnum.Customer))]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var id = HttpContext.User.Identity.Name;

            var result = await _userRepository.ChangePasswordAsync(model, id.ToString());

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Check your password and try again");
                return View(model);
            }

            ViewBag.isSuccess = true;
            return View();
        }
    }
}

WebBanking/Views/Customer/Deposit.cshtml
@model TransactionViewModel
@{ ViewData["Title"] = "Deposit"; }

<h1 class="display-4">Account Number - @Model.AccountNumber</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Deposit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="AccountNumber" hidden />
                <label asp-for="Amount" class="control-label" ></label>
                <input asp-for="Amount"class="form-control"/>
                       @*type="number" step="0.01"/>*@
                <span asp-validation-for="Amount" class="text-danger" ></span>                
            </div>
            <div class="form-group">
                <input type="submit" value="Deposit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Accounts</a>
</div>

@*@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}*@

WebBanking/Views/Customer/DepositConfirm.cshtml
@model TransactionViewModel
@{ ViewData["Title"] = "Deposit"; }

<h1>Account Number - @Model.AccountNumber</h1>

<h3>Review and Confirm Deposit</h3>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Customer" asp-action="DepositConfirm">
            
            <div class="form-group">
                <input asp-for="AccountNumber" hidden />
                <input asp-for="Amount" hidden />

                <label asp-for="AccountNumber" class="control-label">Account Number</label>
                <label asp-for="AccountNumber" class="form-control">@Html.DisplayFor(x => x.AccountNumber)</label>

                <label asp-for="Amount" class="control-label"></label>
                <label asp-for="Amount" class="form-control">@Html.DisplayFor(x => x.Amount)</label>

                
            </div>
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-success" />
                <a asp-controller="Customer" asp-action="Index" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Accounts</a>
</div>

@*@section Scripts {
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    }*@

WebBanking/Views/Customer/Details.cshtml
@model WebBanking.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TFN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TFN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Suburb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Suburb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.CustomerID">Edit</a>
</div>

WebBanking/Views/Customer/Edit.cshtml
@model WebBanking.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Customer Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TFN" class="control-label"></label>
                <input asp-for="TFN" class="form-control" />
                <span asp-validation-for="TFN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Suburb" class="control-label"></label>
                <input asp-for="Suburb" class="form-control" />
                <span asp-validation-for="Suburb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postcode" class="control-label"></label>
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-controller="Signup" asp-action="ChangePassword" asp-route-id=@Model.CustomerID class="btn btn-primary">Change Password</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

WebBanking/Views/Customer/Index.cshtml
@model WebBanking.Models.Customer

@{
    ViewData["Title"] = "Accounts";
}

<h1>Accounts</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.Accounts.FirstOrDefault().AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Accounts.FirstOrDefault().Type)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Accounts.FirstOrDefault().Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Accounts) {
            <tr>
                <td>
                @Html.DisplayFor(modelItem => item.AccountNumber)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.Balance)
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-controller="Account" asp-action="Deposit" asp-route-id="@item.AccountNumber">Deposit</a>
                    <a class="btn btn-primary btn-sm" asp-controller="Account" asp-action="Withdraw" asp-route-id="@item.AccountNumber">Withdraw</a>
                    <a class="btn btn-primary btn-sm" asp-action="Statements" asp-route-id="@item.AccountNumber">Statements</a>

                </td>
        </tr>
}
    </tbody>
</table>

WebBanking/Views/Customer/Statements.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common
@model IPagedList<Transaction>
@{
    ViewData["Title"] = "Statements";
}

<div>
    <h1>Transactions for account number @Model.First().AccountNumber </h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(x => x[0].TransactionTimeUtc)</th>
                <th>@Html.DisplayNameFor(x => x[0].Comment)</th>
                <th>@Html.DisplayNameFor(x => x[0].TransactionType)</th>
                <th>@Html.DisplayNameFor(x => x[0].DestinationAccountNumber)</th>
                <th>@Html.DisplayNameFor(x => x[0].Amount)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in Model)
            {
                <tr>
                    <td>@transaction.TransactionTimeUtc.ToLocalTime().ToString("dd MMM yyyy H:mm")</td>
                    <td>@Html.DisplayFor(x => transaction.Comment)</td>
                    <td>@Html.DisplayFor(x => transaction.TransactionType)</td>
                    <td>@Html.DisplayFor(x => transaction.DestinationAccountNumber)</td>
                    <td>
                        @if (transaction.TransactionType == TransactionType.Withdraw ||
                           transaction.TransactionType == TransactionType.OutgoingTransfer ||
                           transaction.TransactionType == TransactionType.ServiceCharge ||
                           (transaction.TransactionType == TransactionType.BillPay &&
                           transaction.Amount != 0))

                        {<span>- </span>} @Html.DisplayFor(x => transaction.Amount)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @Html.PagedListPager(Model, page => Url.Action("Statements", new { page }),
        new PagedListRenderOptions
            {
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" }
        })
</div>

<div>
    <a asp-action="Index">Back to Accounts</a>
</div>

WebBanking/Views/Customer/TransferForm.cshtml
@model WebBanking.ViewModels.TransactionViewModel

@{ ViewData["Title"] = "Transfer"; }

<h1>Transfer</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="TransferForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <label class="form-control">@Model.AccountNumber</label>
                <input asp-for="AccountNumber" class="form-control" hidden/>
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control"/>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationAccountNumber" class="control-label"></label>
                <input asp-for="DestinationAccountNumber" required class="form-control" />
                <span asp-validation-for="DestinationAccountNumber" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <input type="submit" value="Transfer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}